'use client';
import { useState, useEffect } from 'react';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL || '',
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ''
    );

    export default function Admin() {
      const [upiId, setUpiId] = useState('');
        const [qrUrl, setQrUrl] = useState('');
          const [couponCode, setCouponCode] = useState('');
            const [discount, setDiscount] = useState('');
              const [orders, setOrders] = useState([]);

                // Product Form States
                  const [pName, setPName] = useState('');
                    const [pPrice, setPPrice] = useState('');
                      const [pImg, setPImg] = useState('');
                        const [pCat, setPCat] = useState('Skincare');
                          const [pSizes, setPSizes] = useState('S, M, L, XL');

                            useEffect(() => {
                                fetchOrders();
                                  }, []);

                                    const fetchOrders = async () => {
                                        const { data } = await supabase.from('orders').select('*').order('created_at', { ascending: false });
                                            if (data) setOrders(data);
                                              };

                                                const updateStoreSettings = async () => {
                                                    const { error } = await supabase.from('store_settings').update({ upi_id: upiId, qr_url: qrUrl }).eq('id', 1);
                                                        if (!error) alert('⚙️ Settings Saved!');
                                                          };

                                                            const createCoupon = async () => {
                                                                const { error } = await supabase.from('coupons').insert([{ code: couponCode, discount_percent: Number(discount) }]);
                                                                    if (!error) alert('🎟️ Coupon Created!');
                                                                      };

                                                                        const addProduct = async (e) => {
                                                                            e.preventDefault();
                                                                                const sizesArray = pSizes.split(',').map((s) => s.trim()).filter(Boolean);
                                                                                    const { error } = await supabase.from('products').insert([{
                                                                                          name: pName,
                                                                                                price: Number(pPrice),
                                                                                                      image_url: pImg,
                                                                                                            category: pCat,
                                                                                                                  sizes: sizesArray
                                                                                                                      }]);

                                                                                                                          if (!error) {
                                                                                                                                alert('📦 Product Added!');
                                                                                                                                      setPName(''); setPPrice(''); setPImg('');
                                                                                                                                          } else alert('Error: ' + error.message);
                                                                                                                                            };

                                                                                                                                              return (
                                                                                                                                                  <div style={{ maxWidth: '900px', margin: '20px auto', padding: '16px', fontFamily: 'sans-serif', background: '#f8fafc' }}>
                                                                                                                                                        <h2 style={{ borderBottom: '2px solid #0f172a', paddingBottom: '10px' }}>👑 ZENVRO Admin Panel</h2>

                                                                                                                                                              {/* Product Add Section */}
                                                                                                                                                                    <div style={{ background: '#fff', padding: '16px', borderRadius: '12px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)', marginBottom: '20px' }}>
                                                                                                                                                                            <h3>➕ Add New Product</h3>
                                                                                                                                                                                    <form onSubmit={addProduct} style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
                                                                                                                                                                                              <input placeholder="Product Title" value={pName} onChange={(e) => setPName(e.target.value)} required style={{ padding: '10px', borderRadius: '8px', border: '1px solid #cbd5e1' }} />
                                                                                                                                                                                                        <input placeholder="Price (₹)" type="number" value={pPrice} onChange={(e) => setPPrice(e.target.value)} required style={{ padding: '10px', borderRadius: '8px', border: '1px solid #cbd5e1' }} />
                                                                                                                                                                                                                  <input placeholder="Image URL (ImgBB / Direct Link)" value={pImg} onChange={(e) => setPImg(e.target.value)} required style={{ padding: '10px', borderRadius: '8px', border: '1px solid #cbd5e1' }} />
                                                                                                                                                                                                                            <select value={pCat} onChange={(e) => setPCat(e.target.value)} style={{ padding: '10px', borderRadius: '8px', border: '1px solid #cbd5e1' }}>
                                                                                                                                                                                                                                        <option value="Skincare">Skincare</option>
                                                                                                                                                                                                                                                    <option value="Audio">Audio / Boat</option>
                                                                                                                                                                                                                                                                <option value="Electronics">Electronics</option>
                                                                                                                                                                                                                                                                            <option value="Fashion">Fashion</option>
                                                                                                                                                                                                                                                                                      </select>
                                                                                                                                                                                                                                                                                                <input placeholder="Sizes / Variants (Comma separated: S, M, L or 50ml, 100ml)" value={pSizes} onChange={(e) => setPSizes(e.target.value)} style={{ gridColumn: 'span 2', padding: '10px', borderRadius: '8px', border: '1px solid #cbd5e1' }} />
                                                                                                                                                                                                                                                                                                          <button type="submit" style={{ gridColumn: 'span 2', background: '#2563eb', color: '#fff', padding: '12px', border: 'none', borderRadius: '8px', fontWeight: 'bold' }}>Save Product 🚀</button>
                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                              {/* Settings & Coupons */}
                                                                                                                                                                                                                                                                                                                                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '20px' }}>
                                                                                                                                                                                                                                                                                                                                            <div style={{ background: '#fff', padding: '16px', borderRadius: '12px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)' }}>
                                                                                                                                                                                                                                                                                                                                                      <h3>⚙️ Payment Settings</h3>
                                                                                                                                                                                                                                                                                                                                                                <input placeholder="UPI ID (e.g. name@upi)" onChange={(e) => setUpiId(e.target.value)} style={{ width: '100%', padding: '8px', marginBottom: '8px', borderRadius: '6px', border: '1px solid #ccc', boxSizing: 'border-box' }} />
                                                                                                                                                                                                                                                                                                                                                                          <input placeholder="QR Code ImgBB URL" onChange={(e) => setQrUrl(e.target.value)} style={{ width: '100%', padding: '8px', marginBottom: '8px', borderRadius: '6px', border: '1px solid #ccc', boxSizing: 'border-box' }} />
                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={updateStoreSettings} style={{ background: '#0f172a', color: '#fff', border: 'none', padding: '8px 12px', borderRadius: '6px', width: '100%' }}>Update UPI/QR</button>
                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ background: '#fff', padding: '16px', borderRadius: '12px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)' }}>
                                                                                                                                                                                                                                                                                                                                                                                                              <h3>🎟️ Create Coupon</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                        <input placeholder="Code (e.g. FIRST50)" onChange={(e) => setCouponCode(e.target.value)} style={{ width: '100%', padding: '8px', marginBottom: '8px', borderRadius: '6px', border: '1px solid #ccc', boxSizing: 'border-box' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                  <input placeholder="Discount %" type="number" onChange={(e) => setDiscount(e.target.value)} style={{ width: '100%', padding: '8px', marginBottom: '8px', borderRadius: '6px', border: '1px solid #ccc', boxSizing: 'border-box' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={createCoupon} style={{ background: '#16a34a', color: '#fff', border: 'none', padding: '8px 12px', borderRadius: '6px', width: '100%' }}>Create Coupon</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Orders View */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ background: '#fff', padding: '16px', borderRadius: '12px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3>📦 Recent Orders ({orders.length})</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {orders.map((o) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div key={o.id} style={{ borderBottom: '1px solid #e2e8f0', padding: '10px 0', fontSize: '13px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style={{ margin: '2px 0' }}><b>Customer:</b> {o.customer_name} ({o.phone})</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p style={{ margin: '2px 0' }}><b>Address:</b> {o.address}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p style={{ margin: '2px 0' }}><b>Payment:</b> <span style={{ color: o.payment_method === 'UPI' ? '#2563eb' : '#d97706', fontWeight: 'bold' }}>{o.payment_method}</span> {o.utr_number ? `(UTR: ${o.utr_number})` : ''}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p style={{ margin: '2px 0', fontWeight: 'bold', color: '#16a34a' }}>Amount: ₹{o.total_amount}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
    