'use client';
import { useState, useRef } from 'react';

const ADMIN_EMAIL = "utkarshpawar789@gmail.com";

export default function Home() {
  const [activeTab, setActiveTab] = useState('home'); // 'home', 'categories', 'cart', 'account'
    const [cartStep, setCartStep] = useState(1); // 1: Cart, 2: Address, 3: Payment
      const [user, setUser] = useState({ 
          name: 'Utkarsh Pawar', 
              email: 'utkarsh@gmail.com', 
                  phone: '+91 9876543210',
                      address: '679, Bairagarh, 3 EME Road, Near Jai Maa Kali Mandir, Bhopal 462030'
                        });
                          
                            const [searchQuery, setSearchQuery] = useState('');
                              const [selectedMainCat, setSelectedMainCat] = useState('Grocery & Kitchen');
                                const [imageSearchStatus, setImageSearchStatus] = useState(false);
                                  const fileInputRef = useRef(null);

                                    // AI Care Bot State
                                      const [aiOpen, setAiOpen] = useState(false);
                                        const [aiInput, setAiInput] = useState('');
                                          const [chatLogs, setChatLogs] = useState([
                                              { sender: 'bot', text: 'Hello Utkarsh! Welcome to ZENVRO Care 🤖. Send your Order ID (e.g. #ZENVRO-101) for live delivery tracking.' }
                                                ]);

                                                  // Product Catalog (BigBasket, AJIO, Flipkart Combined)
                                                    const [products] = useState([
                                                        { id: 101, name: 'boAt Storm Call 3 Plus Smartwatch w/ Turn Navigation', brand: 'boAt', section: 'Electronics & Gadgets', price: 1299, originalPrice: 7499, image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=500', rating: 4.8 },
                                                            { id: 102, name: 'GHAR SOAPS MAGIC SOAP 300 GM', brand: 'Ghar Soaps', section: 'Bath, Body & Care', price: 258, originalPrice: 525, image: 'https://images.unsplash.com/photo-1607006482602-50b6988093f3?w=500', rating: 4.7 },
                                                                { id: 103, name: 'Samsung Galaxy S24 Ultra 5G', brand: 'Samsung', section: 'Mobiles', price: 129999, originalPrice: 144999, image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=500', rating: 4.9 },
                                                                    { id: 104, name: 'Atta, Rice, Dal & Fortune Oil Combo Pack', brand: 'Fortune', section: 'Grocery & Kitchen', price: 850, originalPrice: 1200, image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500', rating: 4.6 }
                                                                      ]);

                                                                        const [cart, setCart] = useState([
                                                                            { ...products[0], qty: 1, size: 'Free Size' }
                                                                              ]);

                                                                                // Photo Search Logic
                                                                                  const handleImageUpload = (e) => {
                                                                                      const file = e.target.files[0];
                                                                                          if (file) {
                                                                                                setImageSearchStatus(true);
                                                                                                      setTimeout(() => {
                                                                                                              setSearchQuery('Smartwatch');
                                                                                                                      setImageSearchStatus(false);
                                                                                                                            }, 1000);
                                                                                                                                }
                                                                                                                                  };

                                                                                                                                    const mrpTotal = cart.reduce((acc, item) => acc + (item.originalPrice * item.qty), 0);
                                                                                                                                      const orderTotal = cart.reduce((acc, item) => acc + (item.price * item.qty), 0);
                                                                                                                                        const totalDiscount = mrpTotal - orderTotal;

                                                                                                                                          const handleAiSend = () => {
                                                                                                                                              if (!aiInput.trim()) return;
                                                                                                                                                  const txt = aiInput;
                                                                                                                                                      setChatLogs(prev => [...prev, { sender: 'user', text: txt }]);
                                                                                                                                                          setAiInput('');
                                                                                                                                                              setTimeout(() => {
                                                                                                                                                                    setChatLogs(prev => [...prev, { sender: 'bot', text: '✅ Order #ZENVRO-101 is Confirmed & Dispatched! Guaranteed delivery within 7 Days.' }]);
                                                                                                                                                                        }, 600);
                                                                                                                                                                          };
  return (
        <div style={{ backgroundColor: '#f1f5f9', minHeight: '100vh', fontFamily: 'sans-serif', color: '#0f172a', paddingBottom: '75px' }}>
              
                    {/* 🔝 HEADER WITH CAMERA PHOTO SEARCH */}
                          <div style={{ backgroundColor: '#0f172a', padding: '12px 15px', color: '#fff', position: 'sticky', top: 0, zIndex: 40 }}>
                                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                                            <span style={{ fontSize: '18px', fontWeight: '900', color: '#38bdf8', letterSpacing: '1px' }}>ZENVRO STORE</span>
                                                      {user.email === ADMIN_EMAIL && <span style={{ backgroundColor: '#ef4444', fontSize: '9px', padding: '2px 6px', borderRadius: '4px', fontWeight: 'bold' }}>ADMIN</span>}
                                                              </div>

                                                                      {/* Search Input Bar with 📷 Icon */}
                                                                              <div style={{ position: 'relative', display: 'flex', alignItems: 'center' }}>
                                                                                        <input 
                                                                                                    type="text" 
                                                                                                                placeholder="Search or ask a question..." 
                                                                                                                            value={searchQuery}
                                                                                                                                        onChange={(e) => setSearchQuery(e.target.value)}
                                                                                                                                                    style={{ width: '100%', padding: '10px 40px 10px 12px', borderRadius: '20px', border: 'none', fontSize: '12px', boxSizing: 'border-box' }}
                                                                                                                                                              />
                                                                                                                                                                        
                                                                                                                                                                                  <button 
                                                                                                                                                                                              onClick={() => fileInputRef.current.click()} 
                                                                                                                                                                                                          style={{ position: 'absolute', right: '10px', background: 'none', border: 'none', fontSize: '16px', cursor: 'pointer' }}
                                                                                                                                                                                                                      title="Search by Photo"
                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                            📷
                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                <input type="file" ref={fileInputRef} onChange={handleImageUpload} accept="image/*" style={{ display: 'none' }} />
                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                {imageSearchStatus && <div style={{ fontSize: '10px', color: '#38bdf8', marginTop: '4px' }}>🔍 Analyzing photo to match products...</div>}
                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                            {/* 🏠 HOME TAB PAGE */}
                                                                                                                                                                                                                                                                                                  {activeTab === 'home' && (
                                                                                                                                                                                                                                                                                                          <div style={{ padding: '12px' }}>
                                                                                                                                                                                                                                                                                                                    <div style={{ backgroundColor: '#e0f2fe', padding: '12px', borderRadius: '12px', marginBottom: '15px' }}>
                                                                                                                                                                                                                                                                                                                                <h3 style={{ margin: 0, fontSize: '15px', color: '#0369a1' }}>GRAND FREEDOM SALE ⚡</h3>
                                                                                                                                                                                                                                                                                                                                            <p style={{ margin: '4px 0 0 0', fontSize: '11px', color: '#075985' }}>Guaranteed Express Delivery within 7 Days across India!</p>
                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                <h4 style={{ margin: '0 0 10px 0', fontSize: '13px', fontWeight: 'bold' }}>Trending Offers For You</h4>
                                                                                                                                                                                                                                                                                                                                                                          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
                                                                                                                                                                                                                                                                                                                                                                                      {products.map(p => (
                                                                                                                                                                                                                                                                                                                                                                                                    <div key={p.id} style={{ backgroundColor: '#fff', padding: '10px', borderRadius: '10px', border: '1px solid #e2e8f0' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                    <img src={p.image} alt={p.name} style={{ width: '100%', height: '110px', objectFit: 'cover', borderRadius: '6px' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ fontSize: '11px', color: '#0284c7', fontWeight: 'bold', marginTop: '4px' }}>{p.brand}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ fontSize: '11px', fontWeight: 'bold', margin: '2px 0', height: '28px', overflow: 'hidden' }}>{p.name}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ fontSize: '12px', fontWeight: 'bold' }}>₹{p.price} <span style={{ fontSize: '10px', color: '#94a3b8', textDecoration: 'line-through' }}>₹{p.originalPrice}</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={() => setCart([...cart, { ...p, qty: 1, size: 'Free Size' }])} style={{ width: '100%', backgroundColor: '#0284c7', color: '#fff', border: 'none', padding: '6px', borderRadius: '6px', marginTop: '6px', fontSize: '11px', fontWeight: 'bold', cursor: 'pointer' }}>+ Add to Cart</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
      {/* 📋 ALL CATEGORIES TAB (BIGBASKET STYLE) */}
            {activeTab === 'categories' && (
                    <div style={{ padding: '12px' }}>
                              <h3 style={{ margin: '0 0 15px 0', fontSize: '16px', fontWeight: 'bold' }}>Categories</h3>

                                                  {['Fresh', 'Grocery & Kitchen', 'Snacks & Drinks', 'Bath, Body & Care', 'Electronics & Gadgets'].map((catSection) => (
                                                              <div key={catSection} style={{ marginBottom: '20px' }}>
                                                                            <div style={{ fontSize: '14px', fontWeight: 'bold', marginBottom: '8px', color: '#334155' }}>{catSection}</div>
                                                                                          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '10px' }}>
                                                                                                          {products.filter(p => p.section === catSection || catSection === 'Grocery & Kitchen').map(item => (
                                                                                                                            <div key={item.id} style={{ backgroundColor: '#fff', padding: '10px', borderRadius: '10px', border: '1px solid #e2e8f0', display: 'flex', alignItems: 'center', gap: '10px' }}>
                                                                                                                                                <img src={item.image} alt={item.name} style={{ width: '45px', height: '45px', objectFit: 'cover', borderRadius: '6px' }} />
                                                                                                                                                                    <div style={{ fontSize: '11px', fontWeight: 'bold' }}>{item.name}</div>
                                                                                                                                                                                      </div>
                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                        )}
      {/* 🛒 AJIO EXACT CART PAGE WITH WORKING ADDRESS EDIT */}
            {activeTab === 'cart' && (
                    <div style={{ padding: '12px' }}>
                              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
                                          <span style={{ fontSize: '14px', fontWeight: 'bold' }}>CART SUMMARY</span>
                                                      <span style={{ backgroundColor: '#cbd5e1', padding: '2px 8px', borderRadius: '10px', fontSize: '10px', fontWeight: 'bold' }}>STEP {cartStep}/3</span>
                                                                </div>

                                                                          {/* Delivery Address Box */}
                                                                                    <div style={{ backgroundColor: '#fff', padding: '12px', borderRadius: '8px', border: '1px solid #e2e8f0', marginBottom: '10px' }}>
                                                                                                <div style={{ fontSize: '11px', color: '#64748b' }}>Deliver to: <b>{user.name}</b></div>
                                                                                                            <div style={{ fontSize: '11px', color: '#334155', marginTop: '2px' }}>{user.address}</div>
                                                                                                                        <button 
                                                                                                                                      onClick={() => setShowAddressForm(true)} 
                                                                                                                                                    style={{ width: '100%', backgroundColor: '#8b5cf6', color: '#fff', border: 'none', padding: '8px', borderRadius: '6px', fontWeight: 'bold', marginTop: '8px', fontSize: '12px', cursor: 'pointer' }}
                                                                                                                                                                >
                                                                                                                                                                              Add / Change Address
                                                                                                                                                                                          </button>
                                                                                                                                                                                                    </div>

                                                                                                                                                                                                              {/* REAL WORKING ADDRESS FORM POPUP */}
                                                                                                                                                                                                                        {showAddressForm && (
                                                                                                                                                                                                                                    <div style={{ position: 'fixed', inset: 0, backgroundColor: 'rgba(0,0,0,0.7)', zIndex: 60, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '15px' }}>
                                                                                                                                                                                                                                                  <div style={{ backgroundColor: '#fff', padding: '20px', borderRadius: '12px', width: '100%', maxWidth: '360px', boxSizing: 'border-box' }}>
                                                                                                                                                                                                                                                                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
                                                                                                                                                                                                                                                                                    <h4 style={{ margin: 0, fontSize: '14px', fontWeight: 'bold' }}>Enter Delivery Address</h4>
                                                                                                                                                                                                                                                                                                      <button onClick={() => setShowAddressForm(false)} style={{ background: 'none', border: 'none', fontSize: '16px', cursor: 'pointer' }}>✕</button>
                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                      <input 
                                                                                                                                                                                                                                                                                                                                                                        placeholder="Full Name" 
                                                                                                                                                                                                                                                                                                                                                                                          defaultValue={user.name} 
                                                                                                                                                                                                                                                                                                                                                                                                            onChange={e => setUser({...user, name: e.target.value})} 
                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ width: '100%', padding: '8px', marginBottom: '8px', border: '1px solid #cbd5e1', borderRadius: '4px', fontSize: '12px', boxSizing: 'border-box' }} 
                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <textarea 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Full Address (Flat No, Street, City, Pincode)" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  defaultValue={user.address} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={e => setUser({...user, address: e.target.value})} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      rows={3}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{ width: '100%', padding: '8px', marginBottom: '12px', border: '1px solid #cbd5e1', borderRadius: '4px', fontSize: '12px', boxSizing: 'border-box' }} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setShowAddressForm(false)} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ width: '100%', backgroundColor: '#8b5cf6', color: '#fff', border: 'none', padding: '10px', borderRadius: '6px', fontWeight: 'bold', fontSize: '12px', cursor: 'pointer' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Save Address
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Cart Products List */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {cart.map((item, idx) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div key={idx} style={{ backgroundColor: '#fff', padding: '12px', borderRadius: '8px', border: '1px solid #e2e8f0', marginBottom: '10px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ display: 'flex', gap: '10px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img src={item.image} alt={item.name} style={{ width: '70px', height: '70px', objectFit: 'cover', borderRadius: '6px' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ flex: 1 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span style={{ backgroundColor: '#8b5cf6', color: '#fff', fontSize: '9px', padding: '1px 4px', borderRadius: '3px' }}>✓ Mall</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ fontSize: '12px', fontWeight: 'bold', margin: '2px 0' }}>{item.name}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontSize: '13px', fontWeight: 'bold' }}>₹{item.price} <span style={{ fontSize: '10px', color: '#94a3b8', textDecoration: 'line-through' }}>₹{item.originalPrice}</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ fontSize: '10px', color: '#64748b', marginTop: '4px' }}>Size: {item.size} | Qty: {item.qty}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ display: 'flex', borderTop: '1px solid #f1f5f9', marginTop: '8px', paddingTop: '6px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button style={{ flex: 1, background: 'none', border: 'none', fontSize: '11px', color: '#475569', fontWeight: 'bold', cursor: 'pointer' }}>♡ Move to Wishlist</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={() => setCart(cart.filter((_, i) => i !== idx))} style={{ flex: 1, background: 'none', border: 'none', fontSize: '11px', color: '#ef4444', fontWeight: 'bold', cursor: 'pointer' }}>✕ Remove</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Price Details Breakdown */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ backgroundColor: '#fff', padding: '12px', borderRadius: '8px', border: '1px solid #e2e8f0', marginBottom: '10px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ fontSize: '12px', fontWeight: 'bold', marginBottom: '8px' }}>Price Details ({cart.length} Item)</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '11px', marginBottom: '4px' }}><span>Product Price</span><span>+ ₹{mrpTotal}</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '11px', marginBottom: '4px', color: '#16a34a', fontWeight: 'bold' }}><span>Total Discounts</span><span>- ₹{totalDiscount}</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ borderTop: '1px solid #f1f5f9', paddingTop: '6px', display: 'flex', justifyContent: 'space-between', fontSize: '13px', fontWeight: 'bold' }}><span>Order Total</span><span>₹{orderTotal}</span></div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ backgroundColor: '#dcfce7', color: '#15803d', padding: '6px', borderRadius: '4px', fontSize: '10px', fontWeight: 'bold', marginTop: '8px', textAlign: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Yay! Your total discount is ₹{totalDiscount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={() => alert('Order Placed Successfully! Order ID: #ZENVRO-101')} style={{ width: '100%', backgroundColor: '#16a34a', color: '#fff', border: 'none', padding: '12px', borderRadius: '8px', fontWeight: 'bold', fontSize: '14px', cursor: 'pointer' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Proceed to Payment (₹{orderTotal})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
      {/* 👤 MY ACCOUNT TAB PAGE */}
            {activeTab === 'account' && (
                    <div style={{ padding: '12px' }}>
                              <div style={{ backgroundColor: '#fff', padding: '15px', borderRadius: '12px', border: '1px solid #e2e8f0', marginBottom: '15px' }}>
                                          <h2 style={{ margin: 0, fontSize: '18px' }}>{user.name}</h2>
                                                      <p style={{ margin: '4px 0 0 0', fontSize: '12px', color: '#64748b' }}>{user.email} | {user.phone}</p>
                                                                </div>

                                                                          <div style={{ backgroundColor: '#fff', borderRadius: '12px', overflow: 'hidden', border: '1px solid #e2e8f0' }}>
                                                                                      {[
                                                                                                    '📦 Orders & Live Tracking',
                                                                                                                  '♡ Wishlist',
                                                                                                                                '📍 Saved Delivery Addresses',
                                                                                                                                              '💳 Payment Methods',
                                                                                                                                                            '🎧 ZENVRO AI Customer Care Support'
                                                                                                                                                                        ].map((item, idx) => (
                                                                                                                                                                                      <div 
                                                                                                                                                                                                      key={idx} 
                                                                                                                                                                                                                      onClick={() => item.includes('AI') && setAiOpen(true)}
                                                                                                                                                                                                                                      style={{ padding: '14px 16px', borderBottom: '1px solid #f1f5f9', fontSize: '13px', display: 'flex', justifyContent: 'space-between', cursor: 'pointer' }}
                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                    <span>{item}</span> ➔
                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                      )}
      {/* 🤖 AI CUSTOMER CARE BOT FLOATING MODAL */}
            {aiOpen && (
                    <div style={{ position: 'fixed', inset: 0, backgroundColor: 'rgba(0,0,0,0.7)', zIndex: 60, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '15px' }}>
                              <div style={{ backgroundColor: '#fff', width: '100%', maxWidth: '340px', height: '380px', borderRadius: '12px', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
                                          <div style={{ backgroundColor: '#0f172a', color: '#fff', padding: '10px 12px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                                        <span style={{ fontSize: '12px', fontWeight: 'bold' }}>🤖 ZENVRO AI Care Assistant</span>
                                                                      <button onClick={() => setAiOpen(false)} style={{ background: 'none', border: 'none', color: '#fff', fontSize: '16px', cursor: 'pointer' }}>✕</button>
                                                                                  </div>

                                                                                              <div style={{ flex: 1, padding: '10px', overflowY: 'auto' }}>
                                                                                                            {chatLogs.map((l, i) => (
                                                                                                                            <div key={i} style={{ backgroundColor: l.sender === 'user' ? '#0284c7' : '#f1f5f9', color: l.sender === 'user' ? '#fff' : '#000', padding: '6px 10px', borderRadius: '8px', fontSize: '11px', marginBottom: '6px' }}>
                                                                                                                                              {l.text}
                                                                                                                                                              </div>
                                                                                                                                                                            ))}
                                                                                                                                                                                        </div>

                                                                                                                                                                                                    <div style={{ padding: '6px', borderTop: '1px solid #e2e8f0', display: 'flex', gap: '4px' }}>
                                                                                                                                                                                                                  <input value={aiInput} onChange={e => setAiInput(e.target.value)} placeholder="Type Order ID #ZENVRO-101..." style={{ flex: 1, padding: '6px', fontSize: '11px', border: '1px solid #cbd5e1', borderRadius: '4px' }} />
                                                                                                                                                                                                                                <button onClick={handleAiSend} style={{ backgroundColor: '#0284c7', color: '#fff', border: 'none', padding: '6px 10px', fontSize: '11px', borderRadius: '4px', fontWeight: 'bold' }}>Send</button>
                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                          {/* 🤖 Floating AI Bot Button */}
                                                                                                                                                                                                                                                                                <div onClick={() => setAiOpen(true)} style={{ position: 'fixed', bottom: '75px', right: '15px', backgroundColor: '#0284c7', color: '#fff', width: '45px', height: '45px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '20px', cursor: 'pointer', zIndex: 50, boxShadow: '0 4px 10px rgba(0,0,0,0.3)' }}>
                                                                                                                                                                                                                                                                                        🤖
                                                                                                                                                                                                                                                                                              </div>
      {/* 📱 BOTTOM NAVIGATION BAR */}
            <div style={{ position: 'fixed', bottom: 0, left: 0, right: 0, backgroundColor: '#fff', borderTop: '1px solid #e2e8f0', display: 'flex', justifyContent: 'space-around', padding: '8px 0', fontSize: '10px', zIndex: 50 }}>
                    <div onClick={() => setActiveTab('home')} style={{ color: activeTab === 'home' ? '#0284c7' : '#64748b', cursor: 'pointer', textAlign: 'center' }}>🏠<div>Home</div></div>
                            <div onClick={() => setActiveTab('categories')} style={{ color: activeTab === 'categories' ? '#0284c7' : '#64748b', cursor: 'pointer', textAlign: 'center' }}>📋<div>Categories</div></div>
                                    <div onClick={() => setActiveTab('cart')} style={{ color: activeTab === 'cart' ? '#0284c7' : '#64748b', cursor: 'pointer', textAlign: 'center' }}>🛒<div>Cart ({cart.length})</div></div>
                                            <div onClick={() => setActiveTab('account')} style={{ color: activeTab === 'account' ? '#0284c7' : '#64748b', cursor: 'pointer', textAlign: 'center' }}>👤<div>Account</div></div>
                                                  </div>

                                                      </div>
                                                        );
                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                     