'use client';
import { useState, useRef } from 'react';

const ADMIN_EMAIL = "utkarsh@gmail.com";

export default function Home() {
  const [activeTab, setActiveTab] = useState('home'); // 'home', 'categories', 'cart', 'account'
    const [accountSubTab, setAccountSubTab] = useState(null); // 'orders', 'wishlist', 'addresses'
      const [showAddressForm, setShowAddressForm] = useState(false); // Fixes ReferenceError
        
          const [user, setUser] = useState({ 
              name: 'Utkarsh Pawar', 
                  email: 'utkarsh@gmail.com', 
                      phone: '+91 9876543210',
                          address: '679, Bairagarh, 3 EME Road, Near Jai Maa Kali Mandir, Bhopal 462030'
                            });
                              
                                const [searchQuery, setSearchQuery] = useState('');
                                  const [selectedMainCat, setSelectedMainCat] = useState('All');
                                    const [imageSearchStatus, setImageSearchStatus] = useState(false);
                                      const fileInputRef = useRef(null);

                                        // 🤖 AI Care Assistant State
                                          const [aiOpen, setAiOpen] = useState(false);
                                            const [aiInput, setAiInput] = useState('');
                                              const [chatLogs, setChatLogs] = useState([
                                                  { sender: 'bot', text: 'Hello Utkarsh! Welcome to ZENVRO Care 🤖. Send your Order ID (e.g. #ZENVRO-101) for live tracking.' }
                                                    ]);

                                                      // Product Database
                                                        const [products] = useState([
                                                            { id: 101, name: 'boAt Storm Call 3 Plus Smartwatch', brand: 'boAt', section: 'Electronics', price: 1299, originalPrice: 7499, image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=500' },
                                                                { id: 102, name: 'GHAR SOAPS MAGIC SOAP 300 GM', brand: 'Ghar Soaps', section: 'Bath, Body & Care', price: 258, originalPrice: 525, image: 'https://images.unsplash.com/photo-1607006482602-50b6988093f3?w=500' },
                                                                    { id: 103, name: 'Samsung Galaxy S24 Ultra 5G', brand: 'Samsung', section: 'Mobiles', price: 129999, originalPrice: 144999, image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=500' },
                                                                        { id: 104, name: 'Dove Hair Care Shampoo 500ml', brand: 'Dove', section: 'Bath, Body & Care', price: 349, originalPrice: 650, image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=500' }
                                                                          ]);

                                                                            const [cart, setCart] = useState([
                                                                                { ...products[0], qty: 1, size: 'Free Size' }
                                                                                  ]);

                                                                                    // 📷 Photo Search Handler
                                                                                      const handleImageUpload = (e) => {
                                                                                          const file = e.target.files[0];
                                                                                              if (file) {
                                                                                                    setImageSearchStatus(true);
                                                                                                          setTimeout(() => {
                                                                                                                  setSearchQuery('Smartwatch');
                                                                                                                          setImageSearchStatus(false);
                                                                                                                                }, 800);
                                                                                                                                    }
                                                                                                                                      };

                                                                                                                                        const mrpTotal = cart.reduce((acc, item) => acc + (item.originalPrice * item.qty), 0);
                                                                                                                                          const orderTotal = cart.reduce((acc, item) => acc + (item.price * item.qty), 0);
                                                                                                                                            const totalDiscount = mrpTotal - orderTotal;

                                                                                                                                              // 🤖 AI Care Tracking Logic
                                                                                                                                                const handleAiSend = () => {
                                                                                                                                                    if (!aiInput.trim()) return;
                                                                                                                                                        const txt = aiInput;
                                                                                                                                                            setChatLogs(prev => [...prev, { sender: 'user', text: txt }]);
                                                                                                                                                                setAiInput('');
                                                                                                                                                                    setTimeout(() => {
                                                                                                                                                                          if (txt.toUpperCase().includes('ZENVRO') || txt.includes('101')) {
                                                                                                                                                                                  setChatLogs(prev => [...prev, { sender: 'bot', text: '✅ Order #ZENVRO-101 is Confirmed! Package is out for delivery with Guaranteed Express Delivery within 7 Days.' }]);
                                                                                                                                                                                        } else {
                                                                                                                                                                                                setChatLogs(prev => [...prev, { sender: 'bot', text: 'Order not found. Please provide your Order ID like #ZENVRO-101.' }]);
                                                                                                                                                                                                      }
                                                                                                                                                                                                          }, 500);
                                                                                                                                                                                                            };
  return (
        <div style={{ backgroundColor: '#f8fafc', minHeight: '100vh', fontFamily: 'sans-serif', color: '#0f172a', paddingBottom: '75px' }}>
              
                    {/* 🔝 HEADER & PHOTO SEARCH */}
                          <div style={{ backgroundColor: '#0f172a', padding: '12px 15px', color: '#fff', position: 'sticky', top: 0, zIndex: 40 }}>
                                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                                            <span style={{ fontSize: '18px', fontWeight: '900', color: '#38bdf8' }}>ZENVRO STORE</span>
                                                      {user.email === ADMIN_EMAIL && <span style={{ backgroundColor: '#ef4444', fontSize: '9px', padding: '2px 6px', borderRadius: '4px', fontWeight: 'bold' }}>ADMIN</span>}
                                                              </div>

                                                                      <div style={{ position: 'relative', display: 'flex', alignItems: 'center' }}>
                                                                                <input 
                                                                                            type="text" 
                                                                                                        placeholder="Search products or brands..." 
                                                                                                                    value={searchQuery}
                                                                                                                                onChange={(e) => setSearchQuery(e.target.value)}
                                                                                                                                            style={{ width: '100%', padding: '10px 40px 10px 12px', borderRadius: '20px', border: 'none', fontSize: '12px', boxSizing: 'border-box' }}
                                                                                                                                                      />
                                                                                                                                                                <button 
                                                                                                                                                                            onClick={() => fileInputRef.current?.click()} 
                                                                                                                                                                                        style={{ position: 'absolute', right: '10px', background: 'none', border: 'none', fontSize: '16px', cursor: 'pointer' }}
                                                                                                                                                                                                  >
                                                                                                                                                                                                              📷
                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                  <input type="file" ref={fileInputRef} onChange={handleImageUpload} accept="image/*" style={{ display: 'none' }} />
                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                  {imageSearchStatus && <div style={{ fontSize: '10px', color: '#38bdf8', marginTop: '4px' }}>🔍 Analyzing photo to find products...</div>}
                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                              {/* 🏠 HOME TAB */}
                                                                                                                                                                                                                                                                    {activeTab === 'home' && (
                                                                                                                                                                                                                                                                            <div style={{ padding: '12px' }}>
                                                                                                                                                                                                                                                                                      <div style={{ backgroundColor: '#e0f2fe', padding: '12px', borderRadius: '12px', marginBottom: '15px' }}>
                                                                                                                                                                                                                                                                                                  <h3 style={{ margin: 0, fontSize: '15px', color: '#0369a1' }}>GRAND FREEDOM SALE ⚡</h3>
                                                                                                                                                                                                                                                                                                              <p style={{ margin: '4px 0 0 0', fontSize: '11px', color: '#075985' }}>Guaranteed Express Delivery within 7 Days across India!</p>
                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                  <h4 style={{ margin: '0 0 10px 0', fontSize: '13px', fontWeight: 'bold' }}>Recommended For You</h4>
                                                                                                                                                                                                                                                                                                                                            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
                                                                                                                                                                                                                                                                                                                                                        {products.filter(p => p.name.toLowerCase().includes(searchQuery.toLowerCase())).map(p => (
                                                                                                                                                                                                                                                                                                                                                                      <div key={p.id} style={{ backgroundColor: '#fff', padding: '10px', borderRadius: '10px', border: '1px solid #e2e8f0' }}>
                                                                                                                                                                                                                                                                                                                                                                                      <img src={p.image} alt={p.name} style={{ width: '100%', height: '110px', objectFit: 'cover', borderRadius: '6px' }} />
                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontSize: '10px', color: '#0284c7', fontWeight: 'bold', marginTop: '4px' }}>{p.brand}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontSize: '11px', fontWeight: 'bold', margin: '2px 0', height: '28px', overflow: 'hidden' }}>{p.name}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontSize: '12px', fontWeight: 'bold' }}>₹{p.price} <span style={{ fontSize: '10px', color: '#94a3b8', textDecoration: 'line-through' }}>₹{p.originalPrice}</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => setCart([...cart, { ...p, qty: 1, size: 'Free Size' }])} style={{ width: '100%', backgroundColor: '#0284c7', color: '#fff', border: 'none', padding: '6px', borderRadius: '6px', marginTop: '6px', fontSize: '11px', fontWeight: 'bold', cursor: 'pointer' }}>+ Add</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* 📋 CATEGORIES TAB */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {activeTab === 'categories' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ padding: '12px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3 style={{ margin: '0 0 15px 0', fontSize: '16px', fontWeight: 'bold' }}>All Categories</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {['Electronics', 'Bath, Body & Care', 'Mobiles'].map((cat) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div key={cat} style={{ marginBottom: '15px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ fontSize: '13px', fontWeight: 'bold', marginBottom: '8px', color: '#334155' }}>{cat}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '10px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {products.filter(p => p.section === cat).map(item => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div key={item.id} style={{ backgroundColor: '#fff', padding: '10px', borderRadius: '10px', border: '1px solid #e2e8f0', display: 'flex', alignItems: 'center', gap: '8px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <img src={item.image} alt={item.name} style={{ width: '40px', height: '40px', objectFit: 'cover', borderRadius: '6px' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ fontSize: '11px', fontWeight: 'bold' }}>{item.name}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
      {/* 🛒 CART PART 3A1: SUMMARY & ADDRESS */}
            {activeTab === 'cart' && (
                    <div style={{ padding: '12px' }}>
                              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
                                          <span style={{ fontSize: '14px', fontWeight: 'bold' }}>CART SUMMARY</span>
                                                      <span style={{ backgroundColor: '#cbd5e1', padding: '2px 8px', borderRadius: '10px', fontSize: '10px', fontWeight: 'bold' }}>STEP 1/3</span>
                                                                </div>

                                                                          <div style={{ backgroundColor: '#fff', padding: '12px', borderRadius: '8px', border: '1px solid #e2e8f0', marginBottom: '10px' }}>
                                                                                      <div style={{ fontSize: '11px', color: '#64748b' }}>Deliver to: <b>{user.name}</b></div>
                                                                                                  <div style={{ fontSize: '11px', color: '#334155', marginTop: '2px' }}>{user.address}</div>
                                                                                                              <button onClick={() => setShowAddressForm(true)} style={{ width: '100%', backgroundColor: '#8b5cf6', color: '#fff', border: 'none', padding: '8px', borderRadius: '6px', fontWeight: 'bold', marginTop: '8px', fontSize: '12px', cursor: 'pointer' }}>Add / Change Address</button>
                                                                                                                        </div>

                                                                                                                                  {showAddressForm && (
                                                                                                                                              <div style={{ position: 'fixed', inset: 0, backgroundColor: 'rgba(0,0,0,0.7)', zIndex: 60, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '15px' }}>
                                                                                                                                                            <div style={{ backgroundColor: '#fff', padding: '20px', borderRadius: '12px', width: '100%', maxWidth: '340px' }}>
                                                                                                                                                                            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '12px' }}>
                                                                                                                                                                                              <h4 style={{ margin: 0, fontSize: '14px' }}>Edit Address</h4>
                                                                                                                                                                                                                <button onClick={() => setShowAddressForm(false)} style={{ background: 'none', border: 'none', fontSize: '16px' }}>✕</button>
                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                <input placeholder="Name" defaultValue={user.name} onChange={e => setUser({...user, name: e.target.value})} style={{ width: '100%', padding: '8px', marginBottom: '8px', border: '1px solid #ccc' }} />
                                                                                                                                                                                                                                                                <textarea placeholder="Address" defaultValue={user.address} onChange={e => setUser({...user, address: e.target.value})} rows={3} style={{ width: '100%', padding: '8px', marginBottom: '12px', border: '1px solid #ccc' }} />
                                                                                                                                                                                                                                                                                <button onClick={() => setShowAddressForm(false)} style={{ width: '100%', backgroundColor: '#8b5cf6', color: '#fff', padding: '10px', borderRadius: '6px' }}>Save</button>
                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                    )}
          {/* 🛒 CART PART 3A2: ITEMS & PRICE */}
                    {cart.map((item, idx) => (
                                <div key={idx} style={{ backgroundColor: '#fff', padding: '12px', borderRadius: '8px', border: '1px solid #e2e8f0', marginBottom: '10px' }}>
                                              <div style={{ display: 'flex', gap: '10px' }}>
                                                              <img src={item.image} alt={item.name} style={{ width: '70px', height: '70px', borderRadius: '6px' }} />
                                                                              <div style={{ flex: 1 }}>
                                                                                                <div style={{ fontSize: '12px', fontWeight: 'bold' }}>{item.name}</div>
                                                                                                                  <div style={{ fontSize: '13px', fontWeight: 'bold' }}>₹{item.price}</div>
                                                                                                                                  </div>
                                                                                                                                                </div>
                                                                                                                                                              <button onClick={() => setCart(cart.filter((_, i) => i !== idx))} style={{ marginTop: '8px', background: 'none', border: 'none', color: '#ef4444', fontSize: '11px', fontWeight: 'bold' }}>✕ Remove</button>
                                                                                                                                                                          </div>
                                                                                                                                                                                    ))}

                                                                                                                                                                                              <div style={{ backgroundColor: '#fff', padding: '12px', borderRadius: '8px', border: '1px solid #e2e8f0', marginBottom: '10px' }}>
                                                                                                                                                                                                          <div style={{ fontSize: '12px', fontWeight: 'bold', marginBottom: '8px' }}>Price Details ({cart.length} Item)</div>
                                                                                                                                                                                                                      <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '11px' }}><span>Order Total</span><span>₹{orderTotal}</span></div>
                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                          <button onClick={() => alert('Order Placed!')} style={{ width: '100%', backgroundColor: '#16a34a', color: '#fff', padding: '12px', borderRadius: '8px', fontWeight: 'bold' }}>Proceed to Payment</button>
                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                        )}
      {/* 👤 ACCOUNT TAB */}
            {activeTab === 'account' && (
                    <div style={{ padding: '12px' }}>
                              <div style={{ backgroundColor: '#fff', padding: '15px', borderRadius: '12px', border: '1px solid #e2e8f0', marginBottom: '15px' }}>
                                          <h2 style={{ margin: 0, fontSize: '18px' }}>{user.name}</h2>
                                                    </div>
                                                              {accountSubTab ? (
                                                                          <div style={{ backgroundColor: '#fff', padding: '15px', borderRadius: '12px' }}>
                                                                                        <button onClick={() => setAccountSubTab(null)} style={{ background: 'none', border: 'none', color: '#0284c7' }}>❮ Back</button>
                                                                                                      <h4 style={{marginTop: '10px'}}>{accountSubTab === 'orders' ? 'Your Orders' : 'Details'}</h4>
                                                                                                                    <p style={{fontSize: '12px'}}>{accountSubTab === 'orders' ? '📦 Order #ZENVRO-101' : '📍 ' + user.address}</p>
                                                                                                                                </div>
                                                                                                                                          ) : (
                                                                                                                                                      <div style={{ backgroundColor: '#fff', borderRadius: '12px', overflow: 'hidden' }}>
                                                                                                                                                                    <div onClick={() => setAccountSubTab('orders')} style={{ padding: '15px', borderBottom: '1px solid #f1f5f9' }}>📦 Orders ➔</div>
                                                                                                                                                                                  <div onClick={() => setAccountSubTab('addresses')} style={{ padding: '15px', borderBottom: '1px solid #f1f5f9' }}>📍 Addresses ➔</div>
                                                                                                                                                                                                <div onClick={() => setAiOpen(true)} style={{ padding: '15px' }}>🎧 AI Support ➔</div>
                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                    )}
      {/* 🤖 AI BOT & NAV BAR */}
            {aiOpen && (
                    <div style={{ position: 'fixed', inset: 0, backgroundColor: 'rgba(0,0,0,0.7)', zIndex: 60, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                              <div style={{ backgroundColor: '#fff', width: '320px', height: '350px', borderRadius: '12px' }}>
                                          <div style={{ padding: '10px', display: 'flex', justifyContent: 'space-between', backgroundColor: '#0f172a', color: '#fff' }}>
                                                        <span>AI Care</span>
                                                                      <button onClick={() => setAiOpen(false)}>✕</button>
                                                                                  </div>
                                                                                              <div style={{ padding: '10px', height: '250px', overflowY: 'auto' }}>
                                                                                                            {chatLogs.map((l, i) => <div key={i} style={{ padding: '5px', fontSize: '11px' }}>{l.text}</div>)}
                                                                                                                        </div>
                                                                                                                                    <div style={{ padding: '5px', display: 'flex' }}>
                                                                                                                                                  <input value={aiInput} onChange={e => setAiInput(e.target.value)} style={{ flex: 1 }} />
                                                                                                                                                                <button onClick={handleAiSend}>Send</button>
                                                                                                                                                                            </div>
                                                                                                                                                                                      </div>
                                                                                                                                                                                              </div>
                                                                                                                                                                                                    )}

                                                                                                                                                                                                          <div onClick={() => setAiOpen(true)} style={{ position: 'fixed', bottom: '75px', right: '15px', backgroundColor: '#0284c7', color: '#fff', padding: '10px', borderRadius: '50%' }}>🤖</div>

                                                                                                                                                                                                                <div style={{ position: 'fixed', bottom: 0, left: 0, right: 0, backgroundColor: '#fff', borderTop: '1px solid #e2e8f0', display: 'flex', justifyContent: 'space-around', padding: '10px' }}>
                                                                                                                                                                                                                        <div onClick={() => setActiveTab('home')}>🏠 Home</div>
                                                                                                                                                                                                                                <div onClick={() => setActiveTab('categories')}>📋 Cats</div>
                                                                                                                                                                                                                                        <div onClick={() => setActiveTab('cart')}>🛒 Cart</div>
                                                                                                                                                                                                                                                <div onClick={() => setActiveTab('account')}>👤 Acc</div>
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
