'use client';
import { useState, useEffect } from 'react';
import { createClient } from '@supabase/supabase-js';
import Logo from '../components/Logo';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL || '',
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ''
    );

    export default function Home() {
      const [user, setUser] = useState(null);
        const [isLogin, setIsLogin] = useState(false);
          const [phone, setPhone] = useState('');
            const [fullName, setFullName] = useState('');
              const [authError, setAuthError] = useState('');
                const [loading, setLoading] = useState(false);
                  
                    const [products, setProducts] = useState([]);
                      const [cart, setCart] = useState([]);
                        const [isCartOpen, setIsCartOpen] = useState(false);
                          const [isCheckoutOpen, setIsCheckoutOpen] = useState(false);
                            
                              const [address, setAddress] = useState({ house: '', area: '', landmark: '', city: '', state: '', pincode: '' });
                                const [paymentMethod, setPaymentMethod] = useState('COD');
                                  const [utrNumber, setUtrNumber] = useState('');
                                    const [coupon, setCoupon] = useState('');
                                      const [discount, setDiscount] = useState(0);

                                        const [storeSettings, setStoreSettings] = useState({ upi_id: '', qr_url: '' });

                                          useEffect(() => {
                                              const saved = localStorage.getItem('zenvro_user');
                                                  if (saved) setUser(JSON.parse(saved));
                                                      
                                                          supabase.from('products').select('*').then(({ data }) => data && setProducts(data));
                                                              supabase.from('store_settings').select('*').eq('id', 1).single().then(({ data }) => data && setStoreSettings(data));
                                                                }, []);

                                                                  const handleAuth = async (e) => {
                                                                      e.preventDefault();
                                                                          setAuthError('');
                                                                              if (phone.length < 10) return setAuthError('10-digit number required!');
                                                                                  setLoading(true);

                                                                                      if (!isLogin) {
                                                                                            const { data: existing } = await supabase.from('store_users').select('*').eq('phone', phone).single();
                                                                                                  if (existing) { setAuthError('⚠️ Registered number!'); setLoading(false); return; }
                                                                                                        const { error } = await supabase.from('store_users').insert([{ full_name: fullName, phone }]);
                                                                                                              if (error) { setAuthError(error.message); setLoading(false); return; }
                                                                                                                    const u = { phone, fullName };
                                                                                                                          localStorage.setItem('zenvro_user', JSON.stringify(u));
                                                                                                                                setUser(u);
                                                                                                                                    } else {
                                                                                                                                          const { data: existing } = await supabase.from('store_users').select('*').eq('phone', phone).single();
                                                                                                                                                if (!existing) { setAuthError('❌ Account missing!'); setLoading(false); return; }
                                                                                                                                                      const u = { phone: existing.phone, fullName: existing.full_name };
                                                                                                                                                            localStorage.setItem('zenvro_user', JSON.stringify(u));
                                                                                                                                                                  setUser(u);
                                                                                                                                                                      }
                                                                                                                                                                          setLoading(false);
                                                                                                                                                                            };
  const addToCart = (p) => {
        setCart((prev) => {
              const ex = prev.find((x) => x.id === p.id);
                    return ex ? prev.map((x) => (x.id === p.id ? { ...x, quantity: x.quantity + 1 } : x)) : [...prev, { ...p, quantity: 1 }];
                        });
                            setIsCartOpen(true);
                              };

                                const applyCoupon = async () => {
                                    if (!coupon.trim()) return alert('Coupon write!');
                                        const { data } = await supabase.from('coupons').select('*').eq('code', coupon.trim()).single();
                                            if (data) { setDiscount(data.discount_percent); alert(`🎉 ${data.discount_percent}% Discount!`); }
                                                else alert('❌ Invalid Coupon!');
                                                  };

                                                    const rawTotal = cart.reduce((sum, i) => sum + i.price * i.quantity, 0);
                                                      const finalTotal = rawTotal - Math.round((rawTotal * discount) / 100);

                                                        const handleOrder = async (e) => {
                                                            e.preventDefault();
                                                                if (paymentMethod === 'UPI' && !utrNumber.trim()) {
                                                                      return alert('⚠️ Please enter UTR / Transaction ID!');
                                                                          }
                                                                              setLoading(true);
                                                                                  const fullAddr = `${address.house}, ${address.area}, ${address.landmark ? 'Near ' + address.landmark + ', ' : ''}${address.city}, ${address.state} - ${address.pincode}`;
                                                                                      const { error } = await supabase.from('orders').insert([{
                                                                                            customer_name: user?.fullName || 'Customer',
                                                                                                  phone: user?.phone,
                                                                                                        address: fullAddr,
                                                                                                              total_amount: finalTotal,
                                                                                                                    items: cart,
                                                                                                                          payment_method: paymentMethod,
                                                                                                                                utr_number: paymentMethod === 'UPI' ? utrNumber : null,
                                                                                                                                      status: 'Pending'
                                                                                                                                          }]);
                                                                                                                                              setLoading(false);
                                                                                                                                                  if (!error) {
                                                                                                                                                        alert(`🎉 Order Confirm!`);
                                                                                                                                                              setCart([]); setIsCheckoutOpen(false); setIsCartOpen(false); setDiscount(0); setCoupon(''); setUtrNumber('');
                                                                                                                                                                  } else alert('Error: ' + error.message);
                                                                                                                                                                    };

                                                                                                                                                                      if (!user) {
                                                                                                                                                                          return (
                                                                                                                                                                                <div style={{ minHeight: '100vh', background: '#eef2ff', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '16px', fontFamily: 'sans-serif' }}>
                                                                                                                                                                                        <div style={{ width: '100%', maxWidth: '350px', background: '#fff', borderRadius: '20px', padding: '24px 16px', textAlign: 'center' }}>
                                                                                                                                                                                                  <Logo />
                                                                                                                                                                                                            <h3 style={{ margin: '10px 0' }}>ZENVRO Store</h3>
                                                                                                                                                                                                                      <div style={{ display: 'flex', background: '#f3f4f6', borderRadius: '8px', padding: '2px', marginBottom: '12px' }}>
                                                                                                                                                                                                                                  <button onClick={() => setIsLogin(false)} style={{ flex: 1, padding: '6px', border: 'none', borderRadius: '6px', fontWeight: 'bold', background: !isLogin ? '#fff' : 'none' }}>Sign Up</button>
                                                                                                                                                                                                                                              <button onClick={() => setIsLogin(true)} style={{ flex: 1, padding: '6px', border: 'none', borderRadius: '6px', fontWeight: 'bold', background: isLogin ? '#fff' : 'none' }}>Login</button>
                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                  {authError && <p style={{ color: '#dc2626', fontSize: '11px', margin: '0 0 8px 0' }}>{authError}</p>}
                                                                                                                                                                                                                                                                            <form onSubmit={handleAuth} style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                                                                                                                                                                                                                                                                                        {!isLogin && <input type="text" placeholder="Full Name" value={fullName} onChange={(e) => setFullName(e.target.value)} required style={{ padding: '10px', borderRadius: '8px', border: '1px solid #ccc' }} />}
                                                                                                                                                                                                                                                                                                    <div style={{ display: 'flex', border: '1px solid #ccc', borderRadius: '8px', padding: '0 8px', alignItems: 'center' }}>
                                                                                                                                                                                                                                                                                                                  <span style={{ fontSize: '13px', fontWeight: 'bold', paddingRight: '6px' }}>🇮🇳 +91</span>
                                                                                                                                                                                                                                                                                                                                <input type="tel" maxLength="10" placeholder="Mobile" value={phone} onChange={(e) => setPhone(e.target.value.replace(/\D/g, ''))} required style={{ border: 'none', padding: '10px 0', width: '100%', outline: 'none' }} />
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                        <button type="submit" disabled={loading} style={{ background: '#4f46e5', color: '#fff', border: 'none', padding: '10px', borderRadius: '8px', fontWeight: 'bold' }}>{loading ? 'Wait...' : !isLogin ? 'Create Account' : 'Log In'}</button>
                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                      }
  return (
        <div style={{ minHeight: '100vh', background: '#f9fafb', fontFamily: 'sans-serif' }}>
              <header style={{ background: '#fff', padding: '10px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #eee' }}>
                      <Logo />
                              <div style={{ display: 'flex', gap: '6px', alignItems: 'center' }}>
                                        <span style={{ fontSize: '12px', fontWeight: 'bold' }}>👤 {user.fullName || user.phone}</span>
                                                  <button onClick={() => setIsCartOpen(true)} style={{ background: '#4f46e5', color: '#fff', border: 'none', padding: '6px 10px', borderRadius: '12px', fontWeight: 'bold' }}>🛒 ({cart.length})</button>
                                                            <button onClick={() => { localStorage.removeItem('zenvro_user'); setUser(null); }} style={{ background: '#fee2e2', color: '#991b1b', border: 'none', padding: '4px 8px', borderRadius: '6px', fontSize: '10px' }}>Logout</button>
                                                                    </div>
                                                                          </header>

                                                                                <main style={{ maxWidth: '800px', margin: '16px auto', padding: '0 12px' }}>
                                                                                        <h3>Trending Products</h3>
                                                                                                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))', gap: '10px', marginTop: '10px' }}>
                                                                                                          {products.map((p) => (
                                                                                                                      <div key={p.id} style={{ background: '#fff', borderRadius: '10px', padding: '8px', border: '1px solid #eee' }}>
                                                                                                                                    <img src={p.image_url || 'https://picsum.photos/200'} style={{ width: '100%', height: '110px', objectFit: 'cover', borderRadius: '6px' }} />
                                                                                                                                                  <h4 style={{ fontSize: '13px', margin: '6px 0 2px 0' }}>{p.name}</h4>
                                                                                                                                                                <p style={{ fontWeight: 'bold', color: '#4f46e5', margin: 0, fontSize: '13px' }}>₹{p.price}</p>
                                                                                                                                                                              <button onClick={() => addToCart(p)} style={{ width: '100%', background: '#4f46e5', color: '#fff', border: 'none', padding: '6px', borderRadius: '6px', marginTop: '6px', fontWeight: 'bold', fontSize: '12px' }}>Add to Cart</button>
                                                                                                                                                                                          </div>
                                                                                                                                                                                                    ))}
                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                  </main>

                                                                                                                                                                                                                        {isCartOpen && (
                                                                                                                                                                                                                                <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', justifyContent: 'flex-end', zIndex: 20 }}>
                                                                                                                                                                                                                                          <div style={{ width: '280px', background: '#fff', height: '100%', padding: '16px', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                                                                                                                                                                                                                                                                    <h3 style={{ margin: 0 }}>Cart</h3>
                                                                                                                                                                                                                                                                                                    <button onClick={() => setIsCartOpen(false)} style={{ border: 'none', background: 'none' }}>✕</button>
                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                {cart.map((i) => (
                                                                                                                                                                                                                                                                                                                                                <div key={i.id} style={{ borderBottom: '1px solid #eee', padding: '6px 0', fontSize: '12px' }}>
                                                                                                                                                                                                                                                                                                                                                                  <p style={{ fontWeight: 'bold', margin: 0 }}>{i.name}</p>
                                                                                                                                                                                                                                                                                                                                                                                    <p style={{ margin: 0 }}>{i.quantity} x ₹{i.price}</p>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                          {cart.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={() => setIsCheckoutOpen(true)} style={{ width: '100%', background: '#16a34a', color: '#fff', padding: '10px', border: 'none', borderRadius: '8px', fontWeight: 'bold' }}>Checkout (₹{rawTotal})</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
      {isCheckoutOpen && (
                <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', zIndex: 30, padding: '12px', overflowY: 'auto' }}>
                          <div style={{ background: '#fff', width: '100%', maxWidth: '380px', borderRadius: '16px', padding: '16px', margin: '10px auto', boxSizing: 'border-box' }}>
                                      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '10px' }}>
                                                    <h4 style={{ margin: 0 }}>📍 Address & Payment</h4>
                                                                  <button onClick={() => setIsCheckoutOpen(false)} style={{ border: 'none', background: '#fee2e2', padding: '2px 8px', borderRadius: '6px' }}>✕</button>
                                                                              </div>
                                                                                          <form onSubmit={handleOrder} style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                                                                                                        <input placeholder="House/Flat No." required onChange={(e) => setAddress({ ...address, house: e.target.value })} style={{ padding: '8px', borderRadius: '6px', border: '1px solid #ccc' }} />
                                                                                                                      <input placeholder="Street/Area" required onChange={(e) => setAddress({ ...address, area: e.target.value })} style={{ padding: '8px', borderRadius: '6px', border: '1px solid #ccc' }} />
                                                                                                                                    <input placeholder="Landmark (Optional)" onChange={(e) => setAddress({ ...address, landmark: e.target.value })} style={{ padding: '8px', borderRadius: '6px', border: '1px solid #ccc' }} />
                                                                                                                                                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px' }}>
                                                                                                                                                                  <input placeholder="City" required onChange={(e) => setAddress({ ...address, city: e.target.value })} style={{ padding: '8px', borderRadius: '6px', border: '1px solid #ccc' }} />
                                                                                                                                                                                  <input placeholder="State" required onChange={(e) => setAddress({ ...address, state: e.target.value })} style={{ padding: '8px', borderRadius: '6px', border: '1px solid #ccc' }} />
                                                                                                                                                                                                </div>
                                                                                                                                                                                                              <input placeholder="Pin Code" type="number" required onChange={(e) => setAddress({ ...address, pincode: e.target.value })} style={{ padding: '8px', borderRadius: '6px', border: '1px solid #ccc' }} />
                                                                                                                                                                                                                            <div style={{ padding: '8px', background: '#f8fafc', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
                                                                                                                                                                                                                                            <p style={{ margin: '0 0 4px 0', fontSize: '11px', fontWeight: 'bold' }}>Payment Mode:</p>
                                                                                                                                                                                                                                                            <div style={{ display: 'flex', gap: '15px', fontSize: '12px' }}>
                                                                                                                                                                                                                                                                              <label><input type="radio" name="pm" value="COD" checked={paymentMethod === 'COD'} onChange={(e) => setPaymentMethod(e.target.value)} /> Cash on Delivery</label>
                                                                                                                                                                                                                                                                                                <label><input type="radio" name="pm" value="UPI" checked={paymentMethod === 'UPI'} onChange={(e) => setPaymentMethod(e.target.value)} /> UPI Payment</label>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                            {paymentMethod === 'UPI' && (
                                                                                                                                                                                                                                                                                                                                                            <div style={{ background: '#fef3c7', padding: '10px', borderRadius: '8px', border: '1px solid #f59e0b', textAlignment: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                              <p style={{ margin: '0 0 4px 0', fontSize: '12px', fontWeight: 'bold' }}>Pay via UPI ID:</p>
                                                                                                                                                                                                                                                                                                                                                                                                <p style={{ margin: '0 0 8px 0', fontSize: '13px', background: '#fff', padding: '6px', borderRadius: '6px', fontWeight: 'bold', color: '#b45309' }}>{storeSettings.upi_id || 'Pay to Store UPI'}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                  {storeSettings.qr_url && storeSettings.qr_url !== 'https://via.placeholder.com/200' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                      <img src={storeSettings.qr_url} style={{ width: '120px', height: '120px', margin: '0 auto 8px auto', display: 'block', borderRadius: '6px' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input placeholder="Enter Transaction ID (UTR)" value={utrNumber} onChange={(e) => setUtrNumber(e.target.value)} required style={{ padding: '8px', width: '100%', borderRadius: '6px', border: '1px solid #ccc', boxSizing: 'border-box' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ display: 'flex', gap: '4px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input placeholder="Coupon Code" value={coupon} onChange={(e) => setCoupon(e.target.value)} style={{ flex: 1, padding: '6px 8px', borderRadius: '6px', border: '1px solid #ccc' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button type="button" onClick={applyCoupon} style={{ background: '#4f46e5', color: '#fff', border: 'none', padding: '6px 10px', borderRadius: '6px', fontSize: '12px', fontWeight: 'bold' }}>Apply</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ background: '#f1f5f9', padding: '8px', borderRadius: '6px', fontSize: '12px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>Total: ₹{rawTotal}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {discount > 0 && <div style={{ color: '#16a34a', fontWeight: 'bold' }}>Discount ({discount}%): -₹{Math.round((rawTotal * discount) / 100)}</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ fontWeight: 'bold', fontSize: '14px', marginTop: '4px', borderTop: '1px solid #ccc', paddingTop: '4px' }}>Payable: ₹{finalTotal}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button type="submit" disabled={loading} style={{ background: '#16a34a', color: '#fff', padding: '10px', border: 'none', borderRadius: '6px', fontWeight: 'bold', fontSize: '14px', cursor: 'pointer' }}>{loading ? 'Wait...' : 'Confirm Order 🎉'}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
