// components/Logo.js

export default function Logo({ width = 160, height = 40 }) {
  return (
      <div style={{ display: 'inline-flex', alignItems: 'center', gap: '10px', cursor: 'pointer' }}>
            <svg
                    width={height}
                            height={height}
                                    viewBox="0 0 100 100"
                                            fill="none"
                                                    xmlns="http://www.w3.org/2000/svg"
                                                          >
                                                                  <defs>
                                                                            <linearGradient id="zenvroGrad" x1="0%" y1="0%" x2="100%" y2="100%">
                                                                                        <stop offset="0%" stopColor="#6366F1" />
                                                                                                    <stop offset="50%" stopColor="#8B5CF6" />
                                                                                                                <stop offset="100%" stopColor="#EC4899" />
                                                                                                                          </linearGradient>
                                                                                                                                  </defs>
                                                                                                                                          
                                                                                                                                                  {/* Rounded Hexagon Background */}
                                                                                                                                                          <rect width="100" height="100" rx="28" fill="url(#zenvroGrad)" />
                                                                                                                                                                  
                                                                                                                                                                          {/* Stylized Modern Z */}
                                                                                                                                                                                  <path
                                                                                                                                                                                            d="M28 32H72L36 68H72"
                                                                                                                                                                                                      stroke="#FFFFFF"
                                                                                                                                                                                                                strokeWidth="10"
                                                                                                                                                                                                                          strokeLinecap="round"
                                                                                                                                                                                                                                    strokeLinejoin="round"
                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                            {/* Sparkle Dot */}
                                                                                                                                                                                                                                                                    <circle cx="70" cy="32" r="5" fill="#F43F5E" />
                                                                                                                                                                                                                                                                          </svg>

                                                                                                                                                                                                                                                                                <span
                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                  fontSize: '22px',
                                                                                                                                                                                                                                                                                                            fontWeight: '900',
                                                                                                                                                                                                                                                                                                                      letterSpacing: '-0.5px',
                                                                                                                                                                                                                                                                                                                                background: 'linear-gradient(135deg, #4F46E5 0%, #7C3AED 50%, #DB2777 100%)',
                                                                                                                                                                                                                                                                                                                                          WebkitBackgroundClip: 'text',
                                                                                                                                                                                                                                                                                                                                                    WebkitTextFillColor: 'transparent',
                                                                                                                                                                                                                                                                                                                                                              fontFamily: 'system-ui, -apple-system, sans-serif',
                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                    ZENVRO
                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                